# Generated by Django 4.2.7 on 2026-04-08 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_userinvitation_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="trial_period_days",
            field=models.IntegerField(
                choices=[
                    (0, "No Trial"),
                    (7, "7 Days"),
                    (15, "15 Days"),
                    (30, "30 Days"),
                    (60, "60 Days"),
                    (90, "90 Days"),
                ],
                default=15,
                help_text="Number of days for free trial period",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="config_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
