# Generated by Django 4.2.7 on 2026-04-13 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("firms", "0003_firm_logo_firm_partner_firm_practice_areas_and_more"),
        ("accounts", "0007_firmjoinlink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfirmrole",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="firm_members",
                to="firms.firm",
            ),
        ),
        migrations.AlterField(
            model_name="userinvitation",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_invitations",
                to="firms.firm",
            ),
        ),
    ]
