# Generated by Django 4.2.7 on 2026-04-23 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("firms", "0003_add_logo_registration_practice_areas"),
        ("accounts", "0010_customuser_case_fee_customuser_consultation_fee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="consultation_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="One-time co nsultation fee",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AdvocateParalegalAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "advocate",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "advocate"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_paralegals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paralegal_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advocate_paralegal_assignments",
                        to="firms.firm",
                    ),
                ),
                (
                    "paralegal",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "paralegal"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_advocates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["advocate", "firm"],
                        name="accounts_ad_advocat_709825_idx",
                    ),
                    models.Index(
                        fields=["paralegal", "firm"],
                        name="accounts_ad_paraleg_280fec_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="accounts_ad_is_acti_f20e9c_idx"
                    ),
                ],
                "unique_together": {("advocate", "paralegal", "firm")},
            },
        ),
    ]
