# Generated by Django 4.2.7 on 2026-05-04 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_firmjoinlink_solo_advocate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firmjoinlink",
            name="solo_advocate",
        ),
        migrations.AlterField(
            model_name="firmjoinlink",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
