# Generated by Django 4.2.7 on 2026-05-04 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("firms", "0003_add_logo_registration_practice_areas"),
        ("accounts", "0013_firmjoinlink_firm_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advocateparalegalassignment",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advocate_paralegal_assignments",
                to="firms.firm",
            ),
        ),
    ]
