# Generated by Django 4.2.7 on 2026-05-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0005_invoice_total_amount_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advocateinvoice",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total amount to be paid",
                max_digits=12,
            ),
        ),
    ]
