# Generated by Django 4.2.7 on 2026-05-05 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("firms", "0003_add_logo_registration_practice_areas"),
        ("billing", "0006_fix_advocate_invoice_total_amount_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advocateinvoice",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advocate_invoices",
                to="firms.firm",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="firms.firm",
            ),
        ),
    ]
