# Generated by Django 4.2.7 on 2026-05-05 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("firms", "0003_add_logo_registration_practice_areas"),
        ("billing", "0007_allow_null_firm_on_invoices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="firms.firm",
            ),
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_entries",
                to="firms.firm",
            ),
        ),
    ]
