# Generated by Django 4.2.7 on 2026-04-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="enable_api_access",
            field=models.BooleanField(default=False, help_text="Enable API access"),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="enable_billing",
            field=models.BooleanField(
                default=True, help_text="Enable billing & invoicing module"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="enable_calendar",
            field=models.BooleanField(default=True, help_text="Enable calendar events"),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="enable_documents",
            field=models.BooleanField(
                default=True, help_text="Enable document management"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="enable_reports",
            field=models.BooleanField(
                default=False, help_text="Enable advanced reports & analytics"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_admins",
            field=models.IntegerField(
                default=2, help_text="Maximum number of admins allowed"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_advocates",
            field=models.IntegerField(
                default=1, help_text="Maximum number of advocates allowed"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_branches",
            field=models.IntegerField(
                default=1, help_text="Maximum number of branches"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_clients",
            field=models.IntegerField(
                default=50, help_text="Maximum number of clients"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_paralegals",
            field=models.IntegerField(
                default=2, help_text="Maximum number of paralegals allowed"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="max_users",
            field=models.IntegerField(
                default=5, help_text="Maximum total team members"
            ),
        ),
    ]
