# Generated by Django 4.2.7 on 2026-04-13 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="client",
            name="assigned_advocate",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"user_type": "advocate"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_clients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="brief_summary",
            field=models.TextField(
                blank=True, help_text="Brief summary of the client's legal matter"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="user_account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
