# Generated by Django 4.2.7 on 2026-04-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_alter_client_options_client_assigned_advocate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="client_profiles/"
            ),
        ),
    ]
