# Generated by Django 4.2.7 on 2026-04-16 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0008_alter_case_additional_expenses_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("firms", "0003_add_logo_registration_practice_areas"),
        ("clients", "0003_client_profile_image"),
        ("documents", "0002_userdocument_case_userdocument_document_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdocument",
            name="user",
        ),
        migrations.AddField(
            model_name="userdocument",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Client this document is related to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_documents",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="userdocument",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userdocument",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userdocument",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description or notes about the document",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userdocument",
            name="document_title",
            field=models.CharField(
                blank=True,
                help_text="Title/name of the document",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userdocument",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                help_text="Firm this document belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="firm_documents",
                to="firms.firm",
            ),
        ),
        migrations.AddField(
            model_name="userdocument",
            name="is_deleted",
            field=models.BooleanField(default=False, help_text="Soft delete flag"),
        ),
        migrations.AddField(
            model_name="userdocument",
            name="parent_document",
            field=models.ForeignKey(
                blank=True,
                help_text="Original document if this is a new version",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versions",
                to="documents.userdocument",
            ),
        ),
        migrations.AddField(
            model_name="userdocument",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userdocument",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who uploaded this document",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userdocument",
            name="version",
            field=models.IntegerField(
                default=1, help_text="Version number of this document"
            ),
        ),
        migrations.AlterField(
            model_name="userdocument",
            name="case",
            field=models.ForeignKey(
                blank=True,
                help_text="Case this document is related to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="case_documents",
                to="cases.case",
            ),
        ),
        migrations.AlterField(
            model_name="userdocument",
            name="document_category",
            field=models.CharField(
                blank=True,
                help_text="Custom category for grouping",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userdocument",
            name="document_number",
            field=models.CharField(
                blank=True,
                help_text="Document reference number",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("aadhar", "Aadhar Card"),
                    ("pan", "PAN Card"),
                    ("passport", "Passport"),
                    ("driving_license", "Driving License"),
                    ("bar_certificate", "Bar Council Certificate"),
                    ("degree", "Educational Degree"),
                    ("fir", "FIR"),
                    ("petition", "Petition"),
                    ("evidence", "Evidence"),
                    ("order", "Court Order"),
                    ("agreement", "Agreement"),
                    ("affidavit", "Affidavit"),
                    ("notice", "Legal Notice"),
                    ("contract", "Contract"),
                    ("invoice", "Invoice"),
                    ("receipt", "Receipt"),
                    ("correspondence", "Correspondence"),
                    ("medical_report", "Medical Report"),
                    ("police_report", "Police Report"),
                    ("witness_statement", "Witness Statement"),
                    ("power_of_attorney", "Power of Attorney"),
                    ("vakalatnama", "Vakalatnama"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="userdocument",
            index=models.Index(
                fields=["firm", "is_deleted"], name="documents_u_firm_id_c3a9bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userdocument",
            index=models.Index(
                fields=["client", "is_deleted"], name="documents_u_client__02596f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userdocument",
            index=models.Index(
                fields=["case", "is_deleted"], name="documents_u_case_id_8e3245_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userdocument",
            index=models.Index(
                fields=["uploaded_by", "is_deleted"],
                name="documents_u_uploade_25d511_idx",
            ),
        ),
    ]
