# Generated by Django 4.2.7 on 2026-05-09 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0005_client_firm_nullable"),
        ("cases", "0009_make_firm_nullable_add_solo_advocate"),
        ("firms", "0003_add_logo_registration_practice_areas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0003_remove_userdocument_user_userdocument_client_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name (e.g., Vakalatnama Form)",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the template"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ecourts", "E-Courts Forms"),
                            ("petition", "Petitions"),
                            ("application", "Applications"),
                            ("affidavit", "Affidavits"),
                            ("notice", "Notices"),
                            ("agreement", "Agreements"),
                            ("other", "Other"),
                        ],
                        default="ecourts",
                        max_length=50,
                    ),
                ),
                (
                    "template_file",
                    models.FileField(
                        help_text="Original template file (PDF/DOCX)",
                        upload_to="templates/",
                    ),
                ),
                (
                    "file_size_kb",
                    models.IntegerField(default=0, help_text="File size in KB"),
                ),
                (
                    "template_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON defining fillable fields in the template",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="If true, all advocates can use this template",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="FilledTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "filled_data",
                    models.JSONField(
                        default=dict, help_text="JSON containing filled field values"
                    ),
                ),
                (
                    "generated_file",
                    models.FileField(
                        blank=True,
                        help_text="Generated PDF with filled data",
                        null=True,
                        upload_to="filled_templates/%Y/%m/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("completed", "Completed"),
                            ("shared", "Shared with Client"),
                            ("signed", "Signed"),
                            ("filed", "Filed in Court"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_shared_with_client", models.BooleanField(default=False)),
                ("shared_at", models.DateTimeField(blank=True, null=True)),
                ("client_signed", models.BooleanField(default=False)),
                ("client_signed_at", models.DateTimeField(blank=True, null=True)),
                ("advocate_signed", models.BooleanField(default=False)),
                ("advocate_signed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this document"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filled_templates",
                        to="cases.case",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filled_templates",
                        to="clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_filled_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filled_templates",
                        to="firms.firm",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filled_instances",
                        to="documents.documenttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["case", "status"], name="documents_f_case_id_69f6ee_idx"
                    ),
                    models.Index(
                        fields=["client", "is_shared_with_client"],
                        name="documents_f_client__07a01b_idx",
                    ),
                    models.Index(
                        fields=["firm", "status"], name="documents_f_firm_id_1327d6_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="documenttemplate",
            index=models.Index(
                fields=["category", "is_active"], name="documents_d_categor_ca6c30_idx"
            ),
        ),
    ]
