# Generated by Django 4.2.7 on 2026-04-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="category",
            field=models.CharField(
                choices=[
                    ("court_case", "Court Case"),
                    ("pre_litigation", "Pre-Litigation"),
                ],
                default="court_case",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="cnr_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="case",
            name="court_no",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="case",
            name="district",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="case",
            name="next_hearing_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="petitioner_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="case",
            name="representing",
            field=models.CharField(
                blank=True,
                choices=[
                    ("petitioner", "Petitioner / Complainant"),
                    ("respondent", "Respondent / Accused"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="respondent_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="case",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="case",
            name="case_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("pre_litigation", "Pre-Litigation"),
                    ("running", "Running"),
                    ("disposed", "Disposed off"),
                    ("closed", "Closed"),
                    ("created", "Created"),
                    ("filed", "Filed"),
                    ("evidence", "Evidence"),
                    ("hearing", "Hearing in Progress"),
                    ("judgment", "Judgment Received"),
                ],
                default="created",
                max_length=20,
            ),
        ),
    ]
