# Generated by Django 4.2.7 on 2026-04-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0003_case_category_case_cnr_number_case_court_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="additional_expenses",
            field=models.CharField(default="At actuals", max_length=255),
        ),
        migrations.AddField(
            model_name="case",
            name="case_summary",
            field=models.TextField(blank=True, help_text="Summary shared with client"),
        ),
        migrations.AddField(
            model_name="case",
            name="hearing_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="loe_notes",
            field=models.TextField(
                blank=True, help_text="Internal notes for Letter of Engagement"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="payment_terms",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="case",
            name="stage",
            field=models.CharField(
                choices=[
                    (
                        "initial_consultation",
                        "Initial Consultation and Case Assessment",
                    ),
                    ("document_collection", "Document Collection"),
                    ("case_research", "Case Research and Analysis"),
                    ("notice_drafting", "Notice / Legal Drafting"),
                    ("negotiation", "Negotiation / Mediation"),
                    ("case_filing", "Case Filing"),
                    ("hearing", "Hearing"),
                    ("evidence", "Evidence and Arguments"),
                    ("judgment", "Judgment / Order"),
                    ("appeal", "Appeal"),
                    ("execution", "Execution / Compliance"),
                    ("closed", "Case Closed"),
                ],
                default="initial_consultation",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="total_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
