# Generated by Django 4.2.7 on 2026-04-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0004_case_additional_expenses_case_case_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="billing_type",
            field=models.CharField(
                choices=[
                    ("hourly", "Hourly"),
                    ("flat_fee", "Flat Fee"),
                    ("retainer", "Retainer"),
                    ("contingency", "Contingency"),
                ],
                default="retainer",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="estimated_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="opposing_counsel",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("on_hold", "On Hold"),
                    ("closed", "Closed"),
                    ("won", "Won"),
                    ("lost", "Lost"),
                    ("pre_litigation", "Pre-Litigation"),
                    ("running", "Running"),
                    ("disposed", "Disposed off"),
                    ("created", "Created"),
                    ("filed", "Filed"),
                    ("evidence", "Evidence"),
                    ("hearing", "Hearing in Progress"),
                    ("judgment", "Judgment Received"),
                ],
                default="created",
                max_length=20,
            ),
        ),
    ]
