# Generated by Django 4.2.11 on 2026-04-14 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("firms", "0002_branch"),
        ("cases", "0005_case_billing_type_case_estimated_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="firms.branch",
            ),
        ),
    ]
