# Generated by Django 4.2.7 on 2026-04-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0006_case_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="case_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("on_hold", "On Hold"),
                    ("closed", "Closed"),
                    ("won", "Won"),
                    ("lost", "Lost"),
                    ("pre_litigation", "Pre-Litigation"),
                    ("running", "Running"),
                    ("disposed", "Disposed off"),
                    ("created", "Created"),
                    ("filed", "Filed"),
                    ("evidence", "Evidence"),
                    ("hearing", "Hearing in Progress"),
                    ("judgment", "Judgment Received"),
                ],
                default="created",
                max_length=20,
            ),
        ),
    ]
