# Generated by Django 4.2.7 on 2026-04-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0007_alter_case_case_title_alter_case_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="additional_expenses",
            field=models.CharField(
                blank=True, default="At actuals", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="case_summary",
            field=models.TextField(
                blank=True, help_text="Summary shared with client", null=True
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="cnr_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="court_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="court_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="district",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="judge_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="loe_notes",
            field=models.TextField(
                blank=True,
                help_text="Internal notes for Letter of Engagement",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="opposing_counsel",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="payment_terms",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="petitioner_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="representing",
            field=models.CharField(
                blank=True,
                choices=[
                    ("petitioner", "Petitioner / Complainant"),
                    ("respondent", "Respondent / Accused"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="respondent_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
