# Generated by Django 4.2.7 on 2026-04-30 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("firms", "0003_add_logo_registration_practice_areas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0008_alter_case_additional_expenses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="solo_advocate",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when case is created by an advocate not under any law firm",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solo_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cases",
                to="firms.firm",
            ),
        ),
    ]
